# Android workflow omitted to save build time - only iOS builds run
workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    # Link to your App Store Connect API key (Teams → Integrations → name you gave it)
    integrations:
      app_store_connect: App Store Connect
    # Automatic triggers - builds on push to main branch or when frontend/ changes
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      paths:
        - frontend/**
        - codemagic.yaml
    environment:
      flutter: stable
      xcode: latest
      # Synced from security/deployment.config APP_ID via update-codemagic-config.ps1
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lawsonhutter.counterapp
      groups:
        # Add your environment variables in Codemagic UI under "Environment variables"
        # Required: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        # Optional: API_BASE_URL (defaults to https://dipoll.net/api/counter/)
        - app_store_credentials
      vars:
        # Synced from security/deployment.config via update-codemagic-config.ps1
        API_BASE_URL: "https://lawsonhutter.com/api/counter/"
        APP_ID: "com.lawsonhutter.counterapp"
        # Email for build notifications (sync from deployment.config via update-codemagic-config.ps1)
        CODEMAGIC_EMAIL: "your@email.com"
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd frontend
          flutter pub get
      - name: Verify App Store Connect credentials
        script: |
          echo "Checking App Store Connect credentials..."
          if [ -z "$APP_STORE_CONNECT_ISSUER_ID" ]; then
            echo "❌ APP_STORE_CONNECT_ISSUER_ID not set - add in Codemagic env vars (app_store_credentials)"
            exit 1
          fi
          if [ -z "$APP_STORE_CONNECT_KEY_IDENTIFIER" ]; then
            echo "❌ APP_STORE_CONNECT_KEY_IDENTIFIER not set"
            exit 1
          fi
          if [ -z "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then
            echo "❌ APP_STORE_CONNECT_PRIVATE_KEY not set - paste .p8 file contents"
            exit 1
          fi
          echo "✅ Credentials present"
      - name: Build ipa for distribution (iOS only)
        script: |
          cd frontend
          # Get next build number: use Apple ID if set, else bundle ID; fallback to CM build number
          APPLE_ID="${APP_STORE_APPLE_ID:-$APP_ID}"
          LATEST=$(app-store-connect get-latest-build-number "$APPLE_ID" 2>/dev/null) || LATEST=0
          NEXT=$((LATEST + 1))
          [ "$NEXT" -lt 2 ] && NEXT=2
          echo "Using build number: $NEXT (previous: $LATEST)"
          flutter build ipa --release \
            --dart-define=API_BASE_URL="$API_BASE_URL" \
            --build-name=1.0.0 \
            --build-number=$NEXT
      - name: Verify IPA was created
        script: |
          if [ ! -f frontend/build/ios/ipa/*.ipa ]; then
            echo "IPA file not found!"
            exit 1
          else
            echo "IPA file created successfully"
            ls -lh frontend/build/ios/ipa/*.ipa
          fi
      - name: Upload IPA to App Store Connect
        script: |
          echo "=========================================="
          echo "Uploading IPA to App Store Connect..."
          echo "=========================================="
          
          # Find IPA file
          IPA_PATH=$(find frontend/build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ IPA file not found!"
            exit 1
          fi
          
          echo "✅ IPA found: $IPA_PATH"
          echo "App ID: $APP_ID"
          echo "Issuer ID: ${APP_STORE_CONNECT_ISSUER_ID:0:8}..."
          echo "Key ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo ""
          
          # Save private key to temp file for altool
          PRIVATE_KEY_FILE=$(mktemp)
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > "$PRIVATE_KEY_FILE"
          
          # Use altool to upload
          echo "Uploading using xcrun altool..."
          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_PATH" \
            --apiKey "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" \
            --verbose 2>&1 || {
            echo ""
            echo "❌ Upload failed!"
            echo ""
            echo "Common reasons:"
            echo "  1. App doesn't exist in App Store Connect (MOST COMMON)"
            echo "  2. API credentials are incorrect"
            echo "  3. Bundle ID mismatch"
            echo ""
            echo "ACTION REQUIRED:"
            echo "  Go to https://appstoreconnect.apple.com → My Apps"
            echo "  Create app with Bundle ID: $APP_ID"
            echo "  Then rebuild"
            exit 1
          }
          
          # Clean up
          rm -f "$PRIVATE_KEY_FILE"
          
          echo ""
          echo "✅ Upload successful! Build should appear in App Store Connect shortly."
    artifacts:
      - frontend/build/ios/ipa/*.ipa
      # Only publish iOS artifacts, ignore Android if any exist
    publishing:
      email:
        recipients:
          - $CODEMAGIC_EMAIL
        notify:
          success: true
          failure: false
      app_store_connect:
        # These credentials should be added in Codemagic UI under "Environment variables"
        # Group: app_store_credentials
        # Variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        
        # Try explicit variable references instead of auth: integration
        auth: integration 
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        # Automatically submit to TestFlight (no Mac required!)
        submit_to_testflight: true
        # beta_groups:  # Optional: Specify TestFlight beta groups
        #   - Internal Testing
