# Generated by Django 4.2.27 on 2026-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("click_counter", "0002_question_surveyresponse_answer_responseanswer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="responseanswer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="responseanswer",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="responseanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="responseanswer",
            name="response",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="ResponseAnswer",
        ),
        migrations.DeleteModel(
            name="SurveyResponse",
        ),
    ]
